config/routes.rb
Rails.application.routes.draw do
  get 'uploader/upload'
  post 'uploader/do_file_upload'
  post 'uploader/do_upload'
  get 'sessions/login'
  post 'sessions/do_login'
  get 'sessions/register'
  post 'sessions/do_register'
  delete 'sessions/logout'
  resources :uploads
  resources :books
  resources :users

  root 'sessions#login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible bks-alert-fixed animate fadeOut">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% if message.instance_of? Array %>
      <ul>
        <% message.each do |item| %>
          <li><%= item %></li>
        <% end %>
      </ul>
    <% else %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_renderer.js.erb
$("#flash").html('<%= j render partial: "shared/flash" %>');

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Bookshelf', root_url, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if logged_in %>
        <li class="nav-item">
          <%= link_to 'Books', books_url, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Files', uploads_url, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Upload', uploader_upload_url, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if logged_in %>
        <li class="nav-item mt-2">
          <%= current_user.email %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', sessions_logout_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', sessions_login_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Register', sessions_register_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>