config/routes.rb
Rails.application.routes.draw do
  get 'uploader/upload'
  post 'uploader/do_file_upload'
  post 'uploader/do_upload'
  get 'sessions/login'
  post 'sessions/do_login'
  get 'sessions/register'
  post 'sessions/do_register'
  delete 'sessions/logout'
  resources :uploads
  resources :books
  resources :users

  root 'sessions#login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  has_one_attached :csv_file
end

app/controllers/uploads_controller.rb
require 'csv'

class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    local_params = upload_params.clone
    local_params[:user_id] = current_user.id
    @upload = Upload.new(local_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:filename, :csv_file)
    end
end

app/views/uploads/_form.html.erb
<%= form_with(model: upload, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :csv_file %>
    <%= form.file_field :csv_file, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.csv_file.filename %></td>
        <td><%= link_to 'Download', rails_blob_path(upload.csv_file, disposition: "attachment") %></td>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', uploader_upload_path %>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<%= link_to @upload.csv_file.filename, rails_blob_path(@upload.csv_file, disposition: "attachment") %>
<% if @upload.csv_file.content_type == 'text/csv' %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Date published</th>
      <th>Unique identifier</th>
      <th>Publisher name</th>
    </tr>
    </thead>

    <tbody>
    <% CSV.parse(@upload.csv_file.download, headers: true) do |book| %>
      <tr>
        <td><%= book['title'] %></td>
        <td><%= book['author'] %></td>
        <td><%= book['date_published'] %></td>
        <td><%= book['unique_identifier'] %></td>
        <td><%= book['publisher_name'] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>